# Generated by Django 2.1 on 2018-08-29 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.CharField(default='aaaa', max_length=20, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
